### ISSUE TITLE
Cant install cert - Possible DNS issue with newest version

### ISSUE THREAD

**Issue by adenadoume** [rehmatworks/serverpilot-letsencrypt#50]
Hi get the error
A possible DNS issue found. mysite.com may be pointing to a wrong IP (128.xx.xx.xx)
A possible DNS issue found. www.mysite.com may be pointing to a wrong IP (128.xxx.xx.xx)
SSL not available for this app yet.

Uninstalled all previous, no Cloudflare, just DO - can't install for any APP

any ideas? thanks

**Comment by teraphy** [comment]
I also got this error on a DO droplet using floating IP addresses.
I just commented out the following since the certbot command runs fine.

/usr/local/lib/python3.6/dist-packages/rwssl/utils.py
```python
Starting at line 209 on v2.0.4
#                try:
                runcmd(cmd)
                validdoms.append(domain)
#                except:
#                    ip = socket.gethostbyname(domain)
#                    if validators.ipv4(ip) or validators.ipv6(ip):
#                        errmsg = 'A possible DNS issue found. {} may be pointing to a wrong IP ({})'.format(domain, ip)
#                    else:
#                        errmsg = 'SSL is not available for {} yet.'.format(
#                            domain)
#                    print(colored(errmsg, 'yellow'))
```

**Comment by bikedorkjon** [comment]
I'm getting this error on Linode. 

```
2020-12-28 04:06:39,515:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/certbot/main.py", line 1378, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python3.5/dist-packages/certbot/main.py", line 1265, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/local/lib/python3.5/dist-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/local/lib/python3.5/dist-packages/certbot/client.py", line 405, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/local/lib/python3.5/dist-packages/certbot/client.py", line 348, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/local/lib/python3.5/dist-packages/certbot/client.py", line 384, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/local/lib/python3.5/dist-packages/certbot/auth_handler.py", line 61, in handle_authorizations
    achalls = self._choose_challenges(authzrs)
  File "/usr/local/lib/python3.5/dist-packages/certbot/auth_handler.py", line 185, in _choose_challenges
    if any(isinstance(achall.chall, challenges.TLSSNI01) for achall in achalls):
  File "/usr/local/lib/python3.5/dist-packages/certbot/auth_handler.py", line 185, in <genexpr>
    if any(isinstance(achall.chall, challenges.TLSSNI01) for achall in achalls):
AttributeError: module 'acme.challenges' has no attribute 'TLSSNI01'
2020-12-28 04:06:39,516:ERROR:certbot.log:An unexpected error occurred:
```
